[package]
name = "enclaver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.20", features = ["full"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
tokio-tar = "0.3.0"
futures-util = "0.3.24"
clap = { version = "3.1", features = ["derive"] }
serde_yaml = "0.9.13"
serde_json = "1.0.85"
serde = { version = "1.0", features = ["derive"] }
bollard = "0.13.0"
anyhow = { version = "=1.0.64", features = ["std"] }
tempfile = "3.0"
hyper = "0.14.20"
uuid = { version = "1.1.2", features = ["v4"] }