[package]
name = "enclaver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.20", features = ["full"] }
clap = { version = "3.1", features = ["derive"] }
serde_yaml = "0.9.13"
serde = { version = "1.0", features = ["derive"] }
# thiserror 1.0.35 has a bug preventing it from working on stable
thiserror = "=1.0.34"
bollard = "0.13.0"
anyhow = { version = "=1.0.64", features = ["std"] }
tempfile = "3.0"